# Rime default settings
# encoding: utf-8

config_version: '0.41'

schema_list:
  - schema: vn_quoctu
switcher:
  caption: 􀍟 越喃國字🇻🇳
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    # - F4                   # Xung đột với các phím tắt JetBrains
  save_options:
    - full_shape            # Bảo lưu method toàn chiều rộng
    - ascii_punct           # Bảo lưu method tiếng anh
    - transcription         # Bảo lưu opion hán tự, phồn/giản
    - simplification
    - emoji_suggestion

  fold_options: true        # Tùy chọn gấp để tiết kiệm không gian. Nên gấp true khi có nhiều gói và nên mở rộng sai nếu sử dụng một gói.
  abbreviate_options: true    # tùy chọn viết tắt
  option_list_separator: '・' # Dấu phân cách giữa các tùy chọn

menu:
  page_size: 10

punctuator:
  full_shape:
    __include: punctuation:/full_shape
  half_shape:
    __include: punctuation:/half_shape

key_binder:
  bindings:
    __patch:
      - key_bindings:/emacs_editing
      - key_bindings:/move_by_word_with_tab
      - key_bindings:/paging_with_minus_equal
      - key_bindings:/paging_with_comma_period
      - key_bindings:/numbered_mode_switch

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z`']*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z`']*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  # Define shortcut keys to switch to Western mode
  switch_key:
    Caps_Lock: noop  # Press Caps Lock to directly upload the screen
    Control_L: noop  # Press the left Control key without doing anything
    Control_R: noop  #Press the right Control key without doing anything
    Shift_L: noop  # Press the left Shift key to directly upload the screen
    Shift_R: noop  # Press the right Shift key to temporarily switch to Western mode
  good_old_caps_lock: true  # How to enable the classic Caps Lock to enable Western mode
